=== UKHomeOffice/evw-schemas/src/main/resources/schema/evw-self-serve-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "/",
  "type": "object",
  "required": [
    "membershipNumber",
    "token"
  ],
  "properties": {
      "membershipNumber": {
        "id": "membershipNumber",
        "type": "string",
        "maxLength":25
      },
      "token": {
        "id": "token",
        "type": "string",
        "maxLength":64
      },
      "arrival" : {
        "id" : "arrival",
        "type": "object",
        "required" : [
          "travelBy",
          "portOfArrival",
          "portOfArrivalCode",
          "arrivalDate",
          "arrivalTime",
          "flightDetailsCheck"
        ],
        "properties": {
          "travelBy": {
            "id": "travelBy",
            "type": "string",
            "enum": [
              "Plane",
              "Train",
              "Boat",
              "Land",
              "Private Plane"
            ]
          },
          "departureForUKDate": {
            "id": "departureForUKDate",
            "type": "string",
            "pattern": "^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$"
          },
          "departureForUKTime": {
            "id": "arrivalTime",
            "type": "string",
            "pattern": "^([0-9]{2}):([0-9]{2})$"
          },
          "portOfArrival": {
            "id": "portOfArrival",
            "type": "string",
            "maxLength": 95
          },
          "portOfArrivalCode": {
            "id": "portOfArrivalCode",
            "type": "string",
            "maxLength": 3
          },
          "arrivalTravel": {
            "id": "arrivalTravel",
            "type": "string",
            "maxLength":30
          },
          "arrivalDate": {
            "id": "arrivalDate",
            "type": "string",
            "pattern": "^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$"
          },
          "arrivalTime": {
            "id": "arrivalTime",
            "type": "string",
            "pattern": "^([0-9]{2}):([0-9]{2})$"
          },
          "inwardDepartureCountry": {
            "id": "inwardDepartureCountry",
            "type": "string",
            "maxLength": 3
          },
          "inwardDeparturePort": {
            "id": "inwardDeparturePort",
            "type": "string",
            "maxLength": 95
          },
          "inwardDeparturePortCode": {
            "id": "inwardDeparturePortCode",
            "type": "string",
            "maxLength": 5
          },
          "flightDetailsCheck": {
            "id": "flightDetailsCheck",
            "type": "string",
            "enum": [
              "Yes",
              "No"
            ]
          },
          "travelMethodLand": {
            "id": "travelMethodLand",
            "type": "string",
            "maxLength":50
          }
        },
        "dependencies": {
          "travelBy": {
            "oneOf": [
              {
                "properties": {
                  "travelBy": {
                    "enum": ["Land"]
                  }
                },
                "not": { "required": ["arrivalTravel"] },
                "not": { "required": ["departureForUKDate"] },
                "not": { "required": ["inwardDepartureCountry"] },
                "not": { "required": ["inwardDeparturePort"] }
              },
              {
                "properties": {
                  "travelBy": {
                    "enum": [
                      "Boat",
                      "Plane",
                      "Train",
                      "Private Plane"
                    ]
                  }
                },
                "required": [
                  "arrivalTravel",
                  "departureForUKDate",
                  "inwardDepartureCountry",
                  "inwardDeparturePort",
                  "portOfArrival"
                ]
              }
            ]
          }
        }
      },
      "departure" : {
        "id": "departure",
        "type": "object",
        "properties": {
          "knowDepartureDetails": {
            "id": "knowDepartureDetails",
            "type": "string",
            "enum": [
              "Yes",
              "No"
            ]
          },
          "departureTravel": {
            "id": "departureTravel",
            "type": "string",
            "maxLength":30
          },
          "portOfDeparture": {
            "id": "portOfDeparture",
            "type": "string",
            "maxLength": 95
          },
          "portOfDepartureCode": {
            "id": "portOfDepartureCode",
            "type": "string",
            "maxLength": 3
          },
          "ukDuration": {
            "id": "ukDuration",
            "type": "string"
          }
        },
        "dependencies": {
          "knowDepartureDetails": {
            "oneOf": [
              {
                "properties": {
                  "knowDepartureDetails": {
                    "enum": ["Yes"]
                  }
                },
                "required": [
                  "departureTravel",
                  "portOfDeparture",
                  "departureDate"
                ],
                "not": {"required": ["ukDuration"]}
              },
              {
                "properties": {
                  "knowDepartureDetails": {
                    "enum": ["No"]
                  }
                },
                "required": ["ukDuration"],
                "not": { "required": ["departureTravel"] },
                "not": { "required": ["portOfDeparture"] },
                "not": { "required": ["portOfDepartureCode"] },
                "not": { "required": ["departureDate"] }
              }
            ]
          }
        }
      },
      "accommodation" : {
        "id": "accommodation",
        "type": "object",
        "required" : [
          "ukAddress",
          "ukVisitPhoneNumber"
        ],
        "properties": {
          "ukAddress": {
            "id": "ukAddress",
            "type": "array",
            "items": [
              {
                "id": "0",
                "type": "string",
                "maxLength": 35
              },
              {
                "id": "1",
                "type": "string",
                "maxLength": 35
              },
              {
                "id": "2",
                "type": "string",
                "maxLength": 35
              },
              {
                "id": "3",
                "type": "string",
                "maxLength": 35
              },
              {
                "id": "4",
                "type": "string",
                "maxLength": 35
              }
            ]
          },
          "ukVisitPhoneNumber": {
            "id": "ukVisitPhoneNumber",
            "type": "string",
            "maxLength": 20,
            "minLength": 11,
            "pattern": "^\\+?[0-9-()\\s]+$"
          }
        }
      }
    }
  }

=== UKHomeOffice/evw-schemas/src/main/resources/data/self-serve-good-all.json
{
  "membershipNumber": "C12345",
  "token": "HIDOSA",
  "arrival" : {
    "travelBy" : "Plane",
    "departureForUKDate": "2018-01-01",
    "departureForUKTime": "04:35",
    "portOfArrival": "London Heathrow",
    "portOfArrivalCode": "LHR",
    "arrivalTravel": "BK003",
    "arrivalDate" : "2015-11-26",
    "arrivalTime" : "21:45",
    "inwardDepartureCountry": "FRA",
    "inwardDeparturePort": "Paris",
    "inwardDeparturePortCode": "PSX",
    "flightDetailsCheck" : "No"
  },
  "departure" : {
    "knowDepartureDetails": "No",
    "ukDuration": "1 - 3 months"
  },
  "accommodation" : {
    "ukAddress" : [
      "UkAddress1",
      "UkAddress2",
      "UkAddress3",
      "UkAddress4",
      "Postcode"
    ],
    "ukVisitPhoneNumber": "0793487837429"
  }
}
